import Groq from 'groq-sdk';
import { roastPrompt } from './prompts.js';

export const generateRepoRoast = async (readmeMarkdown, options = {}) => {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error('GROQ_API_KEY is not configured in server environment variables.');
  }

  const groq = new Groq({ apiKey });
  const model = options.model || process.env.GROQ_MODEL || 'openai/gpt-oss-120b';

  const userPrompt = `Project Context: ${options.repoName || 'Uploaded Project'}

Here is the full README.md content to roast:

\`\`\`markdown
${readmeMarkdown}
\`\`\``;

  const chatCompletion = await groq.chat.completions.create({
    messages: [
      { role: 'system', content: roastPrompt },
      { role: 'user', content: userPrompt },
    ],
    model: model,
    temperature: 0.8,
    max_tokens: 1500,
  });

  return chatCompletion.choices[0]?.message?.content || 'No roast generated by LLM.';
};
